Vector = list[float]
Matrix = list[list[float]]
LinearLayer = tuple[Matrix, Vector]
JsonValue = str | int | float | bool | None | list["JsonValue"] | dict[str, "JsonValue"]
JsonObject = dict[str, JsonValue]
